
#访问配置
server:
  port: 8181
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000
    uri-encoding: UTF-8

#Spring配置
spring:
  #  Spring数据库配置
  datasource:
    url: jdbc:mysql://10.10.4.170:3306/venue_reservation_system?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: CVIT2017A412DB!@
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    encoding: utf-8
    cache: false
    servlet:
      content-type: text/html
  #  profiles:
  #    active: @profileActive@
  mvc:
    view:
      prefix: /html/
      suffix: .html
  #热部署
  devtools:
    restart:
      enabled: true
      #设置重启的目录
      additional-paths: src/main/java
      exclude: WEB-INF/** #classpath目录下的WEB-INF文件夹内容修改不重启
  http:
    log-request-details: false

#Mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.genolo.venue_reservation_system.model
  type-aliases-super-type: java.lang.Object
  # 原生mybatis配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    auto-mapping-unknown-column-behavior: warning
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 全局策略配置
  global-config:
    refresh: true
    db-config:
      db-type: mysql
      id-type: id_worker

